In [3]:
import subprocess

root_dir = subprocess.run(f'git rev-parse --show-toplevel', shell=True, stdout=subprocess.PIPE).stdout.decode().strip()
import sys
sys.path.append(root_dir + '/lib')

In [12]:
from pathlib import Path
import pandas as pd
pd.options.display.max_columns=None
import moccalib as ml

In [2]:
path=Path("/work/chuck/mocca/gwiktoro/mocca/src/run/abbas_singlesystem")

In [9]:
pd.read_csv(path / '1-binary-output', sep=' ', header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,35.052,6.0391,1,1,35.052,6.0391,1,1,9.133200e+03,0.057007,9.133200e+03,0.057007,12,13,5.919100,2.141200,6.503600,2.156200,0
1,2.0,35.052,6.0391,1,1,35.052,6.0391,1,1,9.133200e+03,0.057007,9.133200e+03,0.057007,12,13,6.503600,2.156200,7.421000,2.171200,0
2,3.0,35.052,6.0391,1,1,35.052,6.0390,1,1,9.133200e+03,0.057007,9.133200e+03,0.057007,12,13,7.421000,2.171200,9.210900,2.186400,0
3,4.0,35.052,6.0390,1,1,35.052,6.0390,1,1,9.133200e+03,0.057007,9.133200e+03,0.057007,12,13,9.210900,2.186400,14.775000,2.201800,0
4,5.0,35.052,6.0390,1,1,33.674,6.0404,14,1,9.133200e+03,0.057007,9.417000e+03,0.053825,12,13,14.775000,2.201800,0.000143,2.217600,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70.0,33.675,5.9715,14,4,33.676,5.9538,14,4,9.432200e+03,0.053822,9.436200e+03,0.053821,12,13,0.000143,40.272000,0.000143,123.090000,0
70,71.0,33.676,5.9538,14,4,36.714,1.3403,14,12,9.436200e+03,0.053821,2.567700e+09,0.040882,12,13,0.000143,123.090000,0.000156,0.003557,0
71,72.0,36.714,1.3403,14,12,36.714,1.3403,14,12,2.567700e+09,0.040882,2.567700e+09,0.040882,12,13,0.000156,0.003557,0.000156,0.003557,0
72,73.0,36.714,1.3403,14,12,36.714,1.3403,14,12,2.567700e+09,0.040882,2.567700e+09,0.040882,12,13,0.000156,0.003557,0.000156,0.003557,0
73,74.0,36.714,1.3403,14,12,36.714,1.3403,14,12,2.567700e+09,0.040882,2.567700e+09,0.040882,12,13,0.000156,0.003557,0.000156,0.003557,0

In [13]:
ml.read_mocca_file(path / "inter-binevol.dat").query("id1i==12 and id2i==13")

,itype1,idb1i,id1i,id2i,im1i,timevo,sm1i,sm2i,r1i,r2i,slum1i,slum2i,ap1i,ecc1i,r1,ikb1i,ik1i,ik2i,ibstra1i,ibstra2i,iinter1i,iinter2i,ikind1i,idb1f,id1f,id2f,im1f,sm1f,sm2f,r1f,r2f,xlum1f,xlum2f,ap1f,ecc1f,ikb1f,ik1f,ik2f,iexist1,ibstra1f,ibstra2f,iinter1f,iinter2f,ikind1f,ikind2f,nwhich1,im2f,outputId,zeroStep,vr1i,vt1i,vr1f,vt1f,vr2f,vt2f,timenr,pop1i,pop2i,hist1,hist2,mtr1,mtr2
19,0,12,12,13,7,1.0,35.052,6.0391,5.919100,2.141200,1.615300e+05,1211.70000,9.133200e+03,0.057007,1.054,1,1,1,0,0,0,0,2,12,12,13,7,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1,1,1,1,0,0,0,0,2,2,7,7,41,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,1,1,1,100,0,4.095800e-16,-1.832400e-11
39,0,12,12,13,7,2.0,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,82,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,2,1,1,200,0,4.215700e-16,-1.860100e-11
59,0,12,12,13,7,3.0,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,123,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,3,1,1,300,0,4.342100e-16,-1.889400e-11
79,0,12,12,13,7,4.0,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,164,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,4,1,1,400,0,4.475300e-16,-1.920400e-11
99,0,12,12,13,7,5.0,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,33.674,6.0404,0.000143,2.217600,1.000000e-10,1256.20000,9.417000e+03,0.053825,1,14,1,1,0,0,0,0,2,2,7,7,225,0,0.012399,0.70700,0.030020,0.71567,0.030020,0.71567,5,1,1,400,100,4.013000e-16,-1.955700e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,0,12,12,13,7,70.0,33.675,5.9715,0.000143,40.272000,1.000000e-10,7873.00000,9.432200e+03,0.053822,1.054,1,14,4,0,0,0,0,2,12,12,13,7,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1,14,4,1,0,0,0,0,2,2,7,7,2891,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,70,1,1,900,100,1.309500e-09,-3.281400e-08
1419,0,12,12,13,7,71.0,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1.054,1,14,4,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2932,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,71,1,1,900,100,-7.603100e-30,-1.240200e-13
1439,0,12,12,13,7,72.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2973,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,72,1,1,900,100,-7.604400e-30,-5.015000e-14
1459,0,12,12,13,7,73.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3014,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,73,1,1,900,100,-7.605200e-30,-4.315700e-15
1479,0,12,12,13,7,74.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.24102,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3055,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,74,1,1,900,100,-7.605200e-30,-1.603000e-15

In [14]:
path=Path("/work/chuck/mocca/gwiktoro/mocca/src/run/abbas_singlesystem_standev=0.1/")

In [19]:
pd.read_csv(path / '1-binary-output', sep=' ', header=None).loc[700:750]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
700,70.1,33.672,5.9538,14,4,33.672,5.9503,14,4,9.439800e+03,0.056506,9.440500e+03,0.056506,12,13,0.000143,123.130000,0.000143,146.150000,0
701,70.2,33.672,5.9503,14,4,33.673,5.9448,14,5,9.440500e+03,0.056506,9.441500e+03,0.056505,12,13,0.000143,146.150000,0.000143,189.250000,0
702,70.3,33.673,5.9448,14,5,33.674,5.9326,14,5,9.441500e+03,0.056505,9.443400e+03,0.056502,12,13,0.000143,189.250000,0.000143,279.140000,0
703,70.4,33.674,5.9326,14,5,33.682,5.8943,14,6,9.443400e+03,0.056502,9.446100e+03,0.056480,12,13,0.000143,279.140000,0.000143,411.780000,0
704,70.5,33.682,5.8943,14,6,33.698,5.8325,14,6,9.446100e+03,0.056480,9.447700e+03,0.056430,12,13,0.000143,411.780000,0.000143,472.220000,0
705,70.6,33.698,5.8325,14,6,33.725,5.7426,14,6,9.447700e+03,0.056430,9.445500e+03,0.056323,12,13,0.000143,472.220000,0.000143,557.370000,0
706,70.7,33.725,5.7426,14,6,33.780,5.5995,14,6,9.445500e+03,0.056323,9.428900e+03,0.056007,12,13,0.000143,557.370000,0.000143,688.610000,0
707,70.8,33.780,5.5995,14,6,36.712,1.3444,14,6,9.428900e+03,0.056007,2.625100e+09,0.042910,12,13,0.000143,688.610000,0.000156,10.844000,0
708,70.9,36.712,1.3444,14,6,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,10.844000,0.000156,0.003481,0
709,71.0,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
710,71.1,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
711,71.2,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
712,71.3,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
713,71.4,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
714,71.5,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
715,71.6,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
716,71.7,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0
717,71.8,36.712,1.3444,14,12,36.712,1.3444,14,12,2.625100e+09,0.042910,2.625100e+09,0.042910,12,13,0.000156,0.003481,0.000156,0.003481,0

In [13]:
ml.read_mocca_file(path / "inter-binevol.dat").query("id1i==12 and id2i==13")

,itype1,idb1i,id1i,id2i,im1i,timevo,sm1i,sm2i,r1i,r2i,slum1i,slum2i,ap1i,ecc1i,r1,ikb1i,ik1i,ik2i,ibstra1i,ibstra2i,iinter1i,iinter2i,ikind1i,idb1f,id1f,id2f,im1f,sm1f,sm2f,r1f,r2f,xlum1f,xlum2f,ap1f,ecc1f,ikb1f,ik1f,ik2f,iexist1,ibstra1f,ibstra2f,iinter1f,iinter2f,ikind1f,ikind2f,nwhich1,im2f,outputId,zeroStep,vr1i,vt1i,vr1f,vt1f,vr2f,vt2f,timenr,pop1i,pop2i,hist1,hist2,mtr1,mtr2
19,0,12,12,13,7,1.0,35.052,6.0391,5.919100,2.141200,1.615300e+05,1211.70000,9.133200e+03,0.057007,1.054,1,1,1,0,0,0,0,2,12,12,13,7,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1,1,1,1,0,0,0,0,2,2,7,7,41,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,1,1,1,100,0,4.095800e-16,-1.832400e-11
39,0,12,12,13,7,2.0,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,82,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,2,1,1,200,0,4.215700e-16,-1.860100e-11
59,0,12,12,13,7,3.0,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,123,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,3,1,1,300,0,4.342100e-16,-1.889400e-11
79,0,12,12,13,7,4.0,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,164,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,4,1,1,400,0,4.475300e-16,-1.920400e-11
99,0,12,12,13,7,5.0,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,33.674,6.0404,0.000143,2.217600,1.000000e-10,1256.20000,9.417000e+03,0.053825,1,14,1,1,0,0,0,0,2,2,7,7,225,0,0.012399,0.70700,0.030020,0.71567,0.030020,0.71567,5,1,1,400,100,4.013000e-16,-1.955700e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,0,12,12,13,7,70.0,33.675,5.9715,0.000143,40.272000,1.000000e-10,7873.00000,9.432200e+03,0.053822,1.054,1,14,4,0,0,0,0,2,12,12,13,7,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1,14,4,1,0,0,0,0,2,2,7,7,2891,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,70,1,1,900,100,1.309500e-09,-3.281400e-08
1419,0,12,12,13,7,71.0,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1.054,1,14,4,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2932,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,71,1,1,900,100,-7.603100e-30,-1.240200e-13
1439,0,12,12,13,7,72.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2973,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,72,1,1,900,100,-7.604400e-30,-5.015000e-14
1459,0,12,12,13,7,73.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3014,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,73,1,1,900,100,-7.605200e-30,-4.315700e-15
1479,0,12,12,13,7,74.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.24102,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3055,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,74,1,1,900,100,-7.605200e-30,-1.603000e-15

In [20]:
path=Path("/work/chuck/mocca/gwiktoro/mocca/src/run/abbas_singlesystem_fix/")

In [21]:
pd.read_csv(path / '1-binary-output', sep=' ', header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,35.052,6.0391,1,1,35.052,6.0391,1,1,9133.2,0.057007,9133.2,0.057007,12,13,5.919100,2.141200,6.503600,2.156200,0
1,2.0,35.052,6.0391,1,1,35.052,6.0391,1,1,9133.2,0.057007,9133.2,0.057007,12,13,6.503600,2.156200,7.421000,2.171200,0
2,3.0,35.052,6.0391,1,1,35.052,6.0390,1,1,9133.2,0.057007,9133.2,0.057007,12,13,7.421000,2.171200,9.210900,2.186400,0
3,4.0,35.052,6.0390,1,1,35.052,6.0390,1,1,9133.2,0.057007,9133.2,0.057007,12,13,9.210900,2.186400,14.775000,2.201800,0
4,5.0,35.052,6.0390,1,1,33.674,6.0404,14,1,9133.2,0.057007,9417.0,0.053825,12,13,14.775000,2.201800,0.000143,2.217600,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,70.0,33.675,5.9715,14,4,33.676,5.9538,14,4,9432.2,0.053822,9436.2,0.053821,12,13,0.000143,40.272000,0.000143,123.090000,0
70,71.0,33.676,5.9538,14,4,36.714,1.3403,14,12,9436.2,0.053821,644250000.0,0.041652,12,13,0.000143,123.090000,0.000156,0.003557,0
71,72.0,36.714,1.3403,14,12,36.714,1.3403,14,12,644250000.0,0.041652,644250000.0,0.041652,12,13,0.000156,0.003557,0.000156,0.003557,0
72,73.0,36.714,1.3403,14,12,36.714,1.3403,14,12,644250000.0,0.041652,644250000.0,0.041652,12,13,0.000156,0.003557,0.000156,0.003557,0
73,74.0,36.714,1.3403,14,12,36.714,1.3403,14,12,644250000.0,0.041652,644250000.0,0.041652,12,13,0.000156,0.003557,0.000156,0.003557,0

In [13]:
ml.read_mocca_file(path / "inter-binevol.dat").query("id1i==12 and id2i==13")

,itype1,idb1i,id1i,id2i,im1i,timevo,sm1i,sm2i,r1i,r2i,slum1i,slum2i,ap1i,ecc1i,r1,ikb1i,ik1i,ik2i,ibstra1i,ibstra2i,iinter1i,iinter2i,ikind1i,idb1f,id1f,id2f,im1f,sm1f,sm2f,r1f,r2f,xlum1f,xlum2f,ap1f,ecc1f,ikb1f,ik1f,ik2f,iexist1,ibstra1f,ibstra2f,iinter1f,iinter2f,ikind1f,ikind2f,nwhich1,im2f,outputId,zeroStep,vr1i,vt1i,vr1f,vt1f,vr2f,vt2f,timenr,pop1i,pop2i,hist1,hist2,mtr1,mtr2
19,0,12,12,13,7,1.0,35.052,6.0391,5.919100,2.141200,1.615300e+05,1211.70000,9.133200e+03,0.057007,1.054,1,1,1,0,0,0,0,2,12,12,13,7,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1,1,1,1,0,0,0,0,2,2,7,7,41,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,1,1,1,100,0,4.095800e-16,-1.832400e-11
39,0,12,12,13,7,2.0,35.052,6.0391,6.503600,2.156200,1.855100e+05,1219.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,82,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,2,1,1,200,0,4.215700e-16,-1.860100e-11
59,0,12,12,13,7,3.0,35.052,6.0391,7.421000,2.171200,2.200600e+05,1227.80000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,123,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,3,1,1,300,0,4.342100e-16,-1.889400e-11
79,0,12,12,13,7,4.0,35.052,6.0390,9.210900,2.186400,2.697100e+05,1236.60000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1,1,1,1,9,0,0,0,2,2,7,7,164,0,0.012399,0.70700,0.012399,0.70700,0.012399,0.70700,4,1,1,400,0,4.475300e-16,-1.920400e-11
99,0,12,12,13,7,5.0,35.052,6.0390,14.775000,2.201800,3.430700e+05,1245.70000,9.133200e+03,0.057007,1.054,1,1,1,9,0,0,0,2,12,12,13,7,33.674,6.0404,0.000143,2.217600,1.000000e-10,1256.20000,9.417000e+03,0.053825,1,14,1,1,0,0,0,0,2,2,7,7,225,0,0.012399,0.70700,0.030020,0.71567,0.030020,0.71567,5,1,1,400,100,4.013000e-16,-1.955700e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1399,0,12,12,13,7,70.0,33.675,5.9715,0.000143,40.272000,1.000000e-10,7873.00000,9.432200e+03,0.053822,1.054,1,14,4,0,0,0,0,2,12,12,13,7,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1,14,4,1,0,0,0,0,2,2,7,7,2891,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,70,1,1,900,100,1.309500e-09,-3.281400e-08
1419,0,12,12,13,7,71.0,33.676,5.9538,0.000143,123.090000,1.000000e-10,8175.80000,9.436200e+03,0.053821,1.054,1,14,4,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2932,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,71,1,1,900,100,-7.603100e-30,-1.240200e-13
1439,0,12,12,13,7,72.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,5.35460,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,2973,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,72,1,1,900,100,-7.604400e-30,-5.015000e-14
1459,0,12,12,13,7,73.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.75145,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3014,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,73,1,1,900,100,-7.605200e-30,-4.315700e-15
1479,0,12,12,13,7,74.0,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.37295,2.567700e+09,0.040882,1.054,1,14,12,0,0,0,0,2,12,12,13,7,36.714,1.3403,0.000156,0.003557,1.000000e-10,0.24102,2.567700e+09,0.040882,1,14,12,1,0,0,0,0,2,2,7,7,3055,0,0.030020,0.71567,0.030020,0.71567,0.030020,0.71567,74,1,1,900,100,-7.605200e-30,-1.603000e-15